### PR TITLE
Basic bootstrap Design

### PR DESCRIPTION
**Pull request by IrealiTY**
**Done**
- [x] Added a basic template for bootstrap
- [x] Re-formated HTML for more semantic
- [x] Removed in-line styles

**To-do:**
- [ ] Re-structure Javascript from <head> to </body>
- [ ] Fix possible launch issue?:
```
./ffxiv-market config
Traceback (most recent call last):
  File "./ffxiv-market", line 12, in <module>
    CONFIG = json.loads(open(sys.argv[1]).read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 70 column 9 (char 1828)
```

### CODE REVIEW

**Comment by flan** [comment]
I have a couple of small things left to resolve with my changes yesterday (there was a ton of internal restructiring), but I expect that I can have this mostly merged before the day is over.

**Comment by flan** [comment]
And then I saw that you already resolved conflicts. Thanks!

It'll probably be merged mid-day today.

**Comment by IrealiTY** [comment]
Cool :)
Any idea for the issue I encountered? Or do you have the same?

**Comment by flan** [comment]
Haven't checked yet, but I'll probably have a short window to test in about
an hour.

It looks like a JSON deserialising issue, specifically a case where there's
a trailing comma after a property name. (Python is very lenient of trailing
commas for visual consistency, while JSON is extremely strict; I just type
the Python way out of habit)

**Comment by IrealiTY** [comment]
Indeed :D found it, fixed it

**Comment by IrealiTY** [comment]
```
2016-07-06 16:21:10,415:ERROR:tornado.application[1524]:Uncaught exception GET /login?next=%2Fitems (62.75.143.167)
HTTPServerRequest(protocol='http', host='62.75.143.167:1506', method='GET', uri='/login?next=%2Fitems', version='HTTP/1.0', remote_ip='62.75.143.167', headers={'Accept-Language': 'de,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '62.75.143.167:1506', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.60 Safari/537.36', 'Dnt': '1', 'Connection': 'close', 'Cookie': 'auth="2|1:0|10:1467648945|4:auth|4:MQ==|21ff98f1dd3ee2efef1b3647202ee666539942102a5107ede3eb2a6e9bb295df"', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/login.py", line 51, in get
    self._render('login.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/login.html.py", line 23, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:10,416:DEBUG:db[141]:Obtaining database connection
2016-07-06 16:21:10,417:DEBUG:db[148]:Released database connection
2016-07-06 16:21:10,417:ERROR:tornado.application[976]:Uncaught exception in write_error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 974, in send_error
    self.write_error(status_code, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 149, in write_error
    self._render('error.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/error.html.py", line 24, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:10,418:ERROR:tornado.access[1946]:500 GET /login?next=%2Fitems (62.75.143.167) 4.81ms
2016-07-06 16:21:13,159:DEBUG:db[141]:Obtaining database connection
2016-07-06 16:21:13,160:DEBUG:db[148]:Released database connection
2016-07-06 16:21:13,160:ERROR:tornado.application[1524]:Uncaught exception GET /login?next=%2Fitems (62.75.143.167)
HTTPServerRequest(protocol='http', host='62.75.143.167:1506', method='GET', uri='/login?next=%2Fitems', version='HTTP/1.0', remote_ip='62.75.143.167', headers={'Accept-Language': 'de,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '62.75.143.167:1506', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.60 Safari/537.36', 'Dnt': '1', 'Connection': 'close', 'Cookie': 'auth="2|1:0|10:1467648945|4:auth|4:MQ==|21ff98f1dd3ee2efef1b3647202ee666539942102a5107ede3eb2a6e9bb295df"', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/login.py", line 51, in get
    self._render('login.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/login.html.py", line 23, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:13,161:DEBUG:db[141]:Obtaining database connection
2016-07-06 16:21:13,162:DEBUG:db[148]:Released database connection
2016-07-06 16:21:13,162:ERROR:tornado.application[976]:Uncaught exception in write_error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 974, in send_error
    self.write_error(status_code, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 149, in write_error
    self._render('error.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/error.html.py", line 24, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:13,162:ERROR:tornado.access[1946]:500 GET /login?next=%2Fitems (62.75.143.167) 4.01ms
2016-07-06 16:21:14,920:INFO:tornado.access[1946]:302 GET / (62.75.143.167) 0.44ms
2016-07-06 16:21:14,980:INFO:tornado.access[1946]:302 GET /items (62.75.143.167) 0.73ms
2016-07-06 16:21:15,039:DEBUG:db[141]:Obtaining database connection
2016-07-06 16:21:15,040:DEBUG:db[148]:Released database connection
2016-07-06 16:21:15,041:ERROR:tornado.application[1524]:Uncaught exception GET /login?next=%2Fitems (62.75.143.167)
HTTPServerRequest(protocol='http', host='62.75.143.167:1506', method='GET', uri='/login?next=%2Fitems', version='HTTP/1.0', remote_ip='62.75.143.167', headers={'Accept-Language': 'de,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': '62.75.143.167:1506', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.60 Safari/537.36', 'Dnt': '1', 'Connection': 'close', 'Cookie': 'auth="2|1:0|10:1467648945|4:auth|4:MQ==|21ff98f1dd3ee2efef1b3647202ee666539942102a5107ede3eb2a6e9bb295df"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/login.py", line 51, in get
    self._render('login.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/login.html.py", line 23, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:15,041:DEBUG:db[141]:Obtaining database connection
2016-07-06 16:21:15,042:DEBUG:db[148]:Released database connection
2016-07-06 16:21:15,042:ERROR:tornado.application[976]:Uncaught exception in write_error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 974, in send_error
    self.write_error(status_code, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 149, in write_error
    self._render('error.html', context)
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 135, in _render
    self.write(_MAKO_ENGINE.render_page(template, **context))
  File "/var/www/vhosts/phoenixmarket.tk/httpdocs/ffxiv-market/ffxiv_market/handlers/_common.py", line 37, in render_page
    return template.render(CONFIG=CONFIG, DATABASE=DATABASE, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/error.html.py", line 24, in render_body
    runtime._include_file(context, u'header.html', _template_uri)
  File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 752, in _include_file
    callable_(ctx, **_kwargs_for_include(callable_, context._data, **kwargs))
  File "/var/www/vhosts/phoenixmarket.tk/tmp/ffxiv-market/mako_modules/header.html.py", line 32, in render_body
    __M_writer(unicode(site['site_name']))
TypeError: 'Undefined' object has no attribute '__getitem__'
2016-07-06 16:21:15,042:ERROR:tornado.access[1946]:500 GET /login?next=%2Fitems (62.75.143.167) 3.62ms

```

**Comment by flan** [comment]
Those look like the kinds of errors I was expecting: I greatly overhauled the rendering context stuff to better-organise variables.

I'll fix those references and changes to iterators as part of the merging process; everything should be operational later today.

**Comment by flan** [comment]
Merge complete and lightly tested on my site, where it's currently live.

There's currently no quick way to get back to the index-page (previously, clicking the site's name would do that, but it's now a '#' target with no onclick), and there's a lot of scrolling involved to get through each section of items, which hinders the at-a-glance dashboard effect I was going for (with my very limited design skills). I like the cleaner feel it has overall, though.

Lemme know how/where I can help from here. The backend is pretty robust now, so I don't anticipate too many changes in the near future.

**Comment by IrealiTY** [comment]
I see yeah. I'll try more stuff out UI wise and make it more useful.
Didn't play around with a lot of the sub-pages since I was sure you'd make changes :) Will make more changes in the upcoming days but I'm very happy with your new changes and this working base you made.

One thing I noticed is that If you search for an Item it converts it to the ID when you click it. [See here](https://webm.lol/v/1z48605d40)

**Comment by flan** [comment]
I'll do a documentation/logging/commenting pass and clean up that reference tonight.

The ID thing is a quirk of the autocomplete widget, and I'm not sure if there's a built-in way to hide it (I'm sure there's something that can be done like overriding one of its event-handlers). If not, though, I can just have it send the name to the server and retrieve the ID from that. I figured it wouldn't interfere with anything if left alone until the bigger issues were dealt with.

The only feature I'm probably going to add will be a /items/prices-snapshot or something endpoint that provides a JSON dump of the latest prices, partially for debugging and partially so other systems can make use of this server as a data-source, to do things like have a master list of the current prices of items across multiple game servers (so we can finally put those "X is so expensive on Ultros!" comments into context); I'll have a config option to allow it to be turned on/off, though.

If you can think of any data you'd like to have exposed for presentation, let me know and I'll do what I can to figure out how to make it happen. Also let me know if you'd like direct commit access.

**Comment by IrealiTY** [comment]
Maybe I could have a "design" branch on the project so we swing back and forth on layout ideas?

**Comment by IrealiTY** [comment]
Also I think the Graph Render seems broken, as it doesnt generate any graphs :)

**Comment by flan** [comment]
It generates them when there's enough data to have more than one point to display; I'll insert some dummy numbers into Wind Crystal to get it to draw again.

Commit access granted; I'll do all of my future work on separate branches, too.

**Comment by flan** [comment]
http://ffxiv-market.uguu.ca/items/9 (you'll need to re-create your account. I wiped the database when I implemented yesterday's schema changes)

**Comment by IrealiTY** [comment]
hmm... weird http://phoenixmarket.tk/items/1 no graph

**Comment by flan** [comment]
Removing "formatting.js" took out the part that attaches timestamp tooltips to the "X hours ago" elements and the timestamps that render below the graph. It had an on-ready event that iterated over elements and calculated local-time from an element-embedded Unix timestamp.

**Comment by IrealiTY** [comment]
Oh silly me...

**Comment by IrealiTY** [comment]
Could you check again? I re-added the formatting.js its still empty :x

**Comment by flan** [comment]
Oh, I see why you don't have a graph.

Each time-window (data-point) is created using the high-point and low-point of however many seconds are in (28 days / 168 points = 1 point every four hours), defined in the config file. The theory being that the point will be well-represented by the average of its extremes, regardless of how many individual points were recorded within.

Your data was all submitted half an hour ago, so you only have one point, which doesn't make for a very interesting graph. (Maybe it should render anyway, so the page's layout is consistent; suppressing the graph was a decision I made in an older version, when it was rendered as a PNG on each load)

Try this:
```
insert into prices values(9, '2016-07-06 01:49:34', 75, 1);
insert into prices values(9, '2016-07-06 05:49:34', 75, 1); 
insert into prices values(9, '2016-07-05 23:49:34', 75, 1);   
insert into prices values(9, '2016-07-05 19:49:34', 75, 1);   
insert into prices values(9, '2016-07-05 14:49:34', 70, 1);  
insert into prices values(9, '2016-07-05 10:49:34', 65, 1);   
insert into prices values(9, '2016-07-05 06:49:34', 99, 1);    
insert into prices values(9, '2016-07-05 02:49:34', 150, 1);   
insert into prices values(9, '2016-07-04 20:49:34', 0, 1);      
insert into prices values(9, '2016-07-04 16:49:34', 0, 1);  
insert into prices values(9, '2016-07-04 12:49:34', 60, 1);   
insert into prices values(9, '2016-07-04 08:49:34', 62, 1);    
insert into prices values(9, '2016-07-04 03:49:34', 49, 1);
```

**Comment by flan** [comment]
If there's no data between two points, the previous point's value is assumed. Breaks in the graph represent periods when there was no stock for sale on the market, not periods without data.

**Comment by IrealiTY** [comment]
Ah I see, maybe we could change the graph generator to something more fancy?
http://www.chartjs.org/ To have maybe even hourly changes visible?

**Comment by flan** [comment]
I'm definitely open to using something else and I can look into that now that I don't have to focus extensively on the layout stuff.

Google's chart API was just the simplest means to get a prototype going to show to my testers: it looked good enough and it was extremely easy to set up.

**Comment by flan** [comment]
If you want to see hourly data for now, you could increase the data-points value to 672.

168 made sense when rendering a fixed-size image, but it makes less sense with an interactive display.

**Comment by flan** [comment]
Speaking of fancy: http://ultros.xivmb.net/
New domain for primary sites on each server! :D

(I can redirect phoenix to your nameservers when we're a little further along, and I'll use http://xivmb.net/ as a **very** simple master server to compare prices across gameservers for anyone who might get a kick out of that (it'll just scrape current prices hourly from that JSON export I mentioned and plot them on a chart without any real intelligence); I'll also add a /items/base/<id> endpoint so there's link-compatibility with xivdb and Garlond, the latter of which I'll be adding item-page links to soon)

**Pull request merged**
